### ISSUE TITLE
note()

### ISSUE THREAD

**Issue by zaucker** [qooxdoo/qxl.testtapper#2]
It would be helpful for test development to be able to send some infos to the console. E.g.:
```
testFunction: function() {
  let a = someWayToGetA();
  note "a=", a;
  assertEquals(4, a, "a is 4);
}
```
Alternatively, one could use `console.log()` if there was a way to make that appear in the testtapper output. But `note()` would still be useful, as one might not want to see *all* `console.log` generated internally.

**Comment by oetiker** [comment]
`console.log('# My Notes')`
