### ISSUE TITLE
skip()

### ISSUE THREAD

**Issue by zaucker** [qooxdoo/qxl.testtapper#4]
```
testFunction: function() {
  skip();
  skip("Specific reason");
  // optionally code below to be skipped
}
```
should output 
  \# testFunction skipped
  \# testFunction skipped: Specific reason
to the console.

The test should be counted either as  `ok` or better a separate counter `skipped` should be used and output in the test summary (the overall result (`ok` or `nok`) should not be changed by `skip`ped tests.

**Comment by oetiker** [comment]
resolved by #5 - see sample tests
